services:

    #  ================== FORM ================== #

    form.type.seo.page:
        class: Victoire\Bundle\SeoBundle\Form\PageSeoType
        tags:
            - { name: form.type }

    #  ================= HELPER ================= #

    victoire_seo.helper.pageseo_helper:
        class: Victoire\Bundle\SeoBundle\Helper\PageSeoHelper
        arguments:
            - "@victoire_core.helper.business_entity_helper"
            - "@victoire_business_entity.converter.parameter_converter"

    #  ================== MENU ================== #

    victoire_seo.redirection_menu_listener:
        class: Victoire\Bundle\SeoBundle\Listener\RedirectionMenuListener
        arguments: ["@victoire_core.admin_menu_builder"]
        tags:
            - { name: kernel.event_listener, event: victoire_core.build_menu, method: addGlobal, priority: 70 }